services:
  - type: web
    name: mySite
    env: python
    region: Oregon (US West)
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn mySite.wsgi:application"
    preDeployCommand: "python manage.py migrate"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: foadgh_postger
          property: connectionString