services:
  - type: web
    name: mySite
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt"
    preDeployCommand: "python manage.py migrate"
    startCommand: "gunicorn mySite.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: foadgh_postger
          property: connectionString

databases:
  - name: foadgh_postger
    plan: free